#include <iostream>

using namespace std;

/*
Exception Handingling is A C++ exception is a response to an exceptional
circumstance that arises while a program is running, such as an attempt to
divide by zero
*/

int main()
{
    try
    {
        int momsAge = 30;
        int sonsAge = 34;

        if (sonsAge > momsAge)
        /*
        Throwing an exeception is telling that the error showed up
        and you can number the error.
        */
        {
            throw 99;
        }
        /*
        Once this is called you need to catch the program so it dosen't
        freak out and quit, so the catch is gonna turn on where x is the
        number of the throw.
        */
    }
    
    //This catch can only grab ints if you throw a double or anything else at it, it will
    //crash
    catch (int x)
    {
        cout << "Son can't be older than mom. ERROR: " << x << endl;
    }

    try
    {
        int num1;
        cout << "Enter first digit" << endl;
        cin >> num1;

        int num2;
        cout << "Enter second digit" << endl;
        cin >> num2;

        if(num2 == 0)
        {
            throw 2;
        }

        cout << num1/num2 << endl;
    }
    /*
    You can catch multiple error messages. (...) means that if any error happens
    let this catch happen, and then you can have more specific ones. Too
    */

    catch(...)
    {
        cout << "Impossible to divide by zero!" << endl;
    }

    return 0;
}

